package org.pc.trafficviolation.common.exception;

/**
 * Error codes defined for NonSim-Profile module.
 */
public enum TrafficViolationErrorCode {
    UNKNOWN_INTERNAL_ERROR("00102"), //
    DB_CONNECTION_ERROR("00103"), //
    EMA_CONNECTION_ERROR("00104"), //
    B2BUA_CONNECTION_ERROR("00105"), //

    VIMSI_CREATE_NOT_ENOUGH_VIMSI_ERROR("11101"), //
    VIMSI_CREATE_BAD_REQUEST_ERROR("11102"), //
    VIMSI_CREATE_RESOURCE_BUSY_ERROR("11103"), //
    VIMSI_PROVISION_INTERNAL_SERVER_ERROR("11103"), //
    VIMSI_DELETE_BAD_REQUEST_ERROR("11301"), //
    VIMSI_DELETE_ILLEGAL_VIMSI_STATUS_ERROR("11302"), //
    VIMSI_DELETE_EMPTY_VIMSI("11303"), //
    VIMSI_UPDATE_BAD_REQUEST_ERROR("11201"), //
    VIMSI_QUERY_BAD_REQUEST_ERROR("11401"), //
    VIMSI_QUERY_NOT_FOUND("11402"), //

    /** Device profile start */
    DEVICE_PROFILE_QUERY_SIP_CREDENTIALS_NOT_FOUND("16301"), //
    DEVICE_PROFILE_QUERY_SIP_CREDENTIALS_COMMON("16302"), //
    DEVICE_PROFILE_QUERY_SIP_CREDENTIALS_BAD_REQ("16303"), //
    /** VIMSI */
    DEVICE_PROFILE_VIMSI_CREATE_COMMON_ERROR("12101"), //
    DEVICE_PROFILE_VIMSI_CREATE_BAD_REQUEST_ERROR("12102"), //
    DEVICE_PROFILE_VIMSI_UPDATE_COMMON_ERROR("12201"), //
    DEVICE_PROFILE_VIMSI_UPDATE_BAD_REQUEST_ERROR("12202"), //
    DEVICE_PROFILE_VIMSI_UPDATE_UNEXISTED_PROFILE("12203"), //
    DEVICE_PROFILE_VIMSI_UPDATE_EMPTY_SERVICEDATA("12204"), //
    DEVICE_PROFILE_VIMSI_UPDATE_PSAS_BAD_REQUEST_ERROR("12210"), //
    DEVICE_PROFILE_VIMSI_UPDATE_UNEXISTED_CREDENTIAL("12205"), //
    DEVICE_PROFILE_VIMSI_QUERY_NO_PROFILE_FOUND("12301"), //
    DEVICE_PROFILE_VIMSI_QUERY_NO_SIPCREDENTIAL_FOUND("12302"), //
    DEVICE_PROFILE_VIMSI_QUERY_COMMON_ERROR("12303"), //
    DEVICE_PROFILE_VIMSI_QUERY_BAD_REQUEST("12304"), //
    DEVICE_PROFILE_VIMSI_BATCH_QUERY_BAD_REQUEST("12305"), //
    DEVICE_PROFILE_VIMSI_BATCH_QUERY_NO_DATA_FOUND("12306"), //
    DEVICE_PROFILE_GENERIC_VIMSI_QUERY_BAD_REQUEST("12307"), //
    DEVICE_PROFILE_GENERIC_VIMSI_QUERY_NO_PROFILE_FOUND("12308"), //
    DEVICE_PROFILE_VIMSI_QUERY_PSAS_BAD_REQUEST_ERROR("12320"), //
    DEVICE_PROFILE_VIMSI_DELETE_BAD_REQUEST_ERROR("12401"), //
    DEVICE_PROFILE_VIMSI_DELETE_NO_PROFILE_FOUND("12402"), //
    /** ICloudVoWifi */
    DEVICE_PROFILE_UPDATE_VOWIFI_NOT_FOUND("13201"), //
    DEVICE_PROFILE_UPDATE_VOWIFI_COMMON("13202"), //
    DEVICE_PROFILE_UPDATE_VOWIFI_BAD_REQ("13203"), //
    /** Apnstoken */
    DEVICE_PROFILE_APNSTOKEN_CREATE_BAD_REQUEST_ERROR("16101"), //
    DEVICE_PROFILE_APNSTOKEN_UPDATE_BAD_REQUEST_ERROR("16201"), //
    DEVICE_PROFILE_APNSTOKEN_UPDATE_UNEXISTED_PROFILE("16202"), //
    DEVICE_PROFILE_APNSTOKEN_QUERY_BAD_REQUEST_ERROR("16301"), //
    DEVICE_PROFILE_APNSTOKEN_QUERY_NO_PROFILE_FOUND("16302"), //
    DEVICE_PROFILE_APNSTOKEN_BATCH_QUERY_BAD_REQUEST("16303"), //
    DEVICE_PROFILE_APNSTOKEN_BATCH_QUERY_NO_DATA_FOUND("16304"), //
    DEVICE_PROFILE_APNSTOKEN_DELETE_BAD_REQUEST_ERROR("16401"), //
    DEVICE_PROFILE_APNSTOKEN_DELETE_NO_PROFILE_FOUND("16402"), //
    /** VoLTE */
    DEVICE_PROFILE_VOLTE_CREATE_BAD_REQUEST_ERROR("26101"), //
    DEVICE_PROFILE_VOLTE_UPDATE_BAD_REQUEST_ERROR("26201"), //
    DEVICE_PROFILE_VOLTE_UPDATE_NO_PROFILE("26202"), //
    DEVICE_PROFILE_VOLTE_QUERY_BAD_REQUEST_ERROR("26301"), //
    DEVICE_PROFILE_VOLTE_QUERY_NO_PROFILE_FOUND("26302"), //
    DEVICE_PROFILE_VOLTE_DELETE_BAD_REQUEST_ERROR("26401"), //
    DEVICE_PROFILE_VOLTE_DELETE_NO_PROFILE_FOUND("26402"), //
    /** IMSI */
    DEVICE_PROFILE_IMSI_UPDATE_BAD_REQUEST_ERROR("14201"), //
    DEVICE_PROFILE_IMSI_UPDATE_NO_PROFILE_FOUND("14202"), //
    
    DEVICE_PROFILE_IMSI_UPDATE_GENERIC_BAD_REQUEST_ERROR("30201"), //
    DEVICE_PROFILE_IMSI_UPDATE_GENERIC_NO_PROFILE_FOUND("30202"), //
    DEVICE_PROFILE_IMSI_UPDATE_GENERIC_BOTH_PROFILE_EXIST("30203"), //
    DEVICE_PROFILE_IMSI_UPDATE_GENERIC_NO_SIPCREDENTIAL_FOUND("30204"),
    
    /** Device profile end */

    /** EMA start */
    /** Common */
    VIMSI_PROVISION_INVALID_PARAMETER("21101"), //
    VIMSI_PROVISION_INTERNAL_WORKMANAGER_ERROR("21102"), //
    PROFILE_PROVISIONING_INIT_EMA_ERROR("17001"), //
    PROFILE_PROVISIONING_CAI3G_FAULT("17002"), //
    PROFILE_PROVISIONING_COMMON_ERROR("17003"), //
    PROFILE_PROVISIONING_NOSUCHINSTANCE_ERROR("17004"), //
    PROFILE_PROVISIONING_SEND_EXTENAL_ERROR("17005"), //
    AAANSDUSER_CREATE_ALREADY_EXIST_ERROR("17006"), //
    ECAS_CREATE_ALREADY_EXIST_ERROR("17007"), //
    AAANSDUSER_NOT_FOUND_ERROR("17008"), //
    ECAS_ALREADY_ROVOKE("17009"), 
    PROFILE_PROVISIONING_CREATE_BAD_REQUEST_ERROR("17101"), //
    PROFILE_PROVISIONING_CREATE_COMMON_ERROR("17102"), //
    PROFILE_PROVISIONING_CREATE_CAI3G_FAULT("17122"), //
    PROFILE_PROVISIONING_UPDATE_CREATE_EXIST_ERROR("17203"), //
    PROFILE_PROVISIONING_UPDATE_BAD_REQUEST_ERROR("17201"), //
    PROFILE_PROVISIONING_UPDATE_COMMON_ERROR("17202"), //
    PROFILE_PROVISIONING_UPDATE_CAI3G_FAULT("17222"), //
    PROFILE_PROVISIONING_DELETE_BAD_REQUEST_ERROR("17401"), //
    PROFILE_PROVISIONING_DELETE_COMMON_ERROR("17402"), //
    PROFILE_PROVISIONING_DELETE_CAI3G_FAULT("17422"), //
    /** SipUser */
    SIPUSER_UPDATE_COMMON_ERROR("20201"), //
    SIPUSER_UPDATE_BAD_REQUEST_ERROR("20202"), //
    SIPUSER_UPDATE_GATEWAY_TIMEOUT("20203"), //
    /** IMSI account */
    IMSI_ACCOUNT_CREATE_BAD_REQUEST_ERROR("29101"), //
    IMSI_ACCOUNT_CREATE_COMMON_ERROR("29102"), //
    IMSI_ACCOUNT_CREATE_CAI3G_FAULT("29122"), //
    IMSI_ACCOUNT_DELETE_BAD_REQUEST_ERROR("29401"), //
    IMSI_ACCOUNT_DELETE_COMMON_ERROR("29402"), //
    IMSI_ACCOUNT_DELETE_CAI3G_FAULT("29422"), //
    IMSI_ACCOUNT_NOSUCHINSTANCE_ERROR("29004"), //
    /** Connectivity */
    CONNECTIVITY_CREATE_BAD_REQUEST_ERROR("27101"), //
    CONNECTIVITY_CREATE_CAI3G_FAULT("27102"), //
    CONNECTIVITY_CREATE_EXIST_ERROR("27103"), //
    CONNECTIVITY_UPDATE_BAD_REQUEST_ERROR("27201"), //
    CONNECTIVITY_UPDATE_CAI3G_FAULT("27202"), //
    CONNECTIVITY_DELETE_BAD_REQUEST_ERROR("27401"), //
    CONNECTIVITY_DELETE_CAI3G_FAULT("27402"), //
    /** AAA */
    AAA_CREATE_BAD_REQUEST_ERROR("28101"), //
    AAA_CREATE_CAI3G_FAULT("28102"), //
    AAA_UPDATE_BAD_REQUEST_ERROR("28201"), //
    AAA_UPDATE_CAI3G_FAULT("28202"), //
    AAA_UPDATE_INVALID_USER_STATUS("28203"), 
    AAA_GET_BAD_REQUEST_ERROR("28301"), //
    AAA_GET_CAI3G_FAULT("28302"), //
    AAA_DELETE_BAD_REQUEST_ERROR("28401"), //
    AAA_DELETE_CAI3G_FAULT("28402"), //
    /** ECAS */
    ECAS_CREATE_BAD_REQUEST_ERROR("29101"), //
    ECAS_CREATE_CAI3G_FAULT("29102"), //
    ECAS_UPDATE_BAD_REQUEST_ERROR("29201"), //
    ECAS_UPDATE_CAI3G_FAULT("29202"), //
    ECAS_GET_BAD_REQUEST_ERROR("29301"), //
    ECAS_GET_CAI3G_FAULT("29302"), //
    ECAS_DELETE_BAD_REQUEST_ERROR("29401"), //
    ECAS_DELETE_CAI3G_FAULT("29402"), //
    /** HSSMono */
    HSSMONO_UPDATE_BAD_REQUEST_ERROR("30201"), //
    HSSMONO_UPDATE_CAI3G_FAULT("30202"), //
    HSSMONO_GET_BAD_REQUEST_ERROR("30301"), //
    HSSMONO_GET_CAI3G_FAULT("30302"), //
    /** EMA end */

    /** SimAuthorization start */
    SIM_AUTHORIZATION_CREATE_COMMON_ERROR("22101"), //
    SIM_AUTHORIZATION_CREATE_BAD_REQUEST_ERROR("22102"), //
    SIM_AUTHORIZATION_UPDATE_COMMON_ERROR("22201"), //
    SIM_AUTHORIZATION_UPDATE_BAD_REQUEST_ERROR("22202"), //
    SIM_AUTHORIZATION_QUERY_COMMON_ERROR("22301"), //
    SIM_AUTHORIZATION_QUERY_BAD_REQUEST_ERROR("22302"), //
    SIM_AUTHORIZATION_QUERY_NOT_FOUND("22303"), //
    SIM_AUTHORIZATION_DELETE_COMMON_ERROR("22401"), //
    SIM_AUTHORIZATION_DELETE_BAD_REQUEST_ERROR("22402"), //
    SIM_AUTHORIZATION_DELETE_FAILED("22403"), //
    SIM_AUTHORIZATION_UPDATE_IMSI_COMMON_ERROR("15201"), //
    SIM_AUTHORIZATION_UPDATE_IMSI_BAD_REQUEST_ERROR("15202"), //
    /** SimAuthorization end */

    /** SipUser start */
    SIPUSER_CREDENTIAL_QUERY_COMMON_ERROR("25301"), //
    SIPUSER_CREDENTIAL_QUERY_BAD_REQUEST_ERROR("25302"), //
    SIPUSER_CREDENTIAL_QUERY_NOT_FOUND("25303"), //
    SIPUSER_CREDENTIAL_QUERY_DIGEST_ERROR("25304"), //
    SIPUSER_USER_QUERY_COMMON_ERROR("24301"), //
    SIPUSER_USER_QUERY_BAD_REQUEST_ERROR("24302"), //
    SIPUSER_USER_QUERY_NOTFOUND("24303"), //
    SIPUSER_USER_QUERY_BATCH_EXPIRED_COMMON_ERROR("26301"), //
    SIPUSER_USER_QUERY_BATCH_EXPIRED_BAD_REQUEST_ERROR("26302"), //
    SIPUSER_USER_QUERY_BATCH_EXPIRED_NOT_FOUND("26303"), //
    /** SipUser end */

    /** Apnstoken Repository start */
    APNS_TOKEN_CREATE_BAD_REQUEST("23101"), //
    APNS_TOKEN_QUERY_SES_BAD_REQUEST("23301"), //
    APNS_TOKEN_QUERY_SES_EMPTY_RESULT("23302"), //
    APNS_TOKEN_QUERY_BAD_REQUEST("23303"), //
    APNS_TOKEN_QUERY_EMPTY_RESULT("23304"), //
    APNS_TOKEN_UPDATE_BAD_REQUEST("23201"), //
    APNS_TOKEN_UPDATE_ODP_BAD_REQUEST("23211"), //
    APNS_TOKEN_DELETE_BAD_REQUEST("23401"), //
    APNS_TOKEN_DELETE_EMPTY_RESULT("23402"), //
    APNS_TOKEN_QUERY_CLEANUP_BAD_REQUEST_ERROR("23310"), //
    APNS_TOKEN_QUERY_CLEANUP_NO_DATA_FOUND("23311"), //
    /** IMSI sub resource */
    APNS_TOKEN_UPDATE_IMSI_BAD_REQUEST("28201"), //
    APNS_TOKEN_UPDATE_IMSI_EMPTY_RESULT("28202"), //
    /** Apnstoken Repository end */

    /**
     * Task Manager
     */
    TASK_MANAGER_CONFIGURATION_ERROR("30001");

    private String errorCode;

    private TrafficViolationErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

}
